spring.config.import=aws-secretsmanager:/prod/leohanq/db/franchise?prefix=db.
spring.datasource.url=jdbc:${db.engine}://${db.host}:${db.port}/franchise
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
server.port=8080